import {
  defaultTabelaGeralConfig,
  mergeOverlayConfig,
  type FixedStreamOverlayTemplate,
} from '@/lib/streamOverlay'

export const booyahsDiaOverlayTemplate: FixedStreamOverlayTemplate = {
  id: 'booyah',
  slug: 'booyahs-do-dia',
  nome: 'Booyahs do Dia',
  categoria: 'estatisticas',
  descricao: 'Cards com o booyah de cada queda do jogo.',
  config_padrao: mergeOverlayConfig(defaultTabelaGeralConfig, {
    title: 'BOOYAHS DO DIA',
    booyahsDia: {
      mode: 'cards',
      title: 'BOOYAHS DO DIA',
      subtitle: '',
      artImageUrl: '',
      artX: 0,
      artY: 20,
      artW: 1920,
      artH: 260,
      artSideX: 80,
      artSideY: 160,
      artSideW: 720,
      artSideH: 620,
      artFit: 'contain',
      autoFit: true,
      columns: 6,
      containerWidth: 1840,
      cardWidth: 292,
      cardHeight: 470,
      gap: 18,
      x: 36,
      y: 360,
      logoSize: 150,
      background: '#eef3e8',
      accent: '#82a82b',
      text: '#1f2937',
      mutedMapFilter: 'grayscale(1)',
      pendingMapFilter: 'none',
      mapBackgroundUrl: '',
      nameBandBackgroundUrl: '',
      statsBackground: '#ffffff',
      statsBackgroundUrl: '',
      statsText: '#1f2937',
      sideX: 120,
      sideY: 160,
      sideW: 620,
      sideImageUrl: '',
      sideImageSize: 160,
      sideTitleSmall: 'BOOYAHS',
      sideTitleMain: 'DO DIA',
      sideTitleSize: 150,
      sideSmallSize: 54,
      listX: 940,
      listY: 160,
      listW: 820,
      listH: 760,
      listRowHeight: 132,
      listLogoSize: 120,
    },
    theme: {
      primary: '#82a82b',
      accent: '#f97316',
      background: '#eef3e8',
      text: '#1f2937',
    },
    layout: {
      maxRows: 6,
    },
  }),
}
