import {
  defaultTabelaGeralConfig,
  mergeOverlayConfig,
  type FixedStreamOverlayTemplate,
} from '@/lib/streamOverlay'

export const tabelaGeralOverlayTemplate: FixedStreamOverlayTemplate = {
  id: 'tabela-geral',
  slug: 'tabela-geral',
  nome: 'Tabela Geral',
  categoria: 'estatisticas',
  descricao: 'Classificacao geral acumulada do campeonato.',
  config_padrao: mergeOverlayConfig(defaultTabelaGeralConfig, {
    title: 'TABELA GERAL',
    tabelaGeral: {
      mode: 'duplo-inferior',
      backgroundImage: '',
      backgroundOpacity: 100,
      infoImage: {
        enabled: true,
        url: '/stream-overlays/tabela-geral/lgd-tb-geral.png',
        x: 0,
        y: 8,
        w: 1920,
        h: 330,
        opacity: 100,
        fit: 'contain',
      },
    },
    brand: {
      enabled: false,
      imageEnabled: true,
      textEnabled: true,
      name: 'NOME DO CAMPEONATO',
      title: 'TABELA GERAL',
    },
    columns: {
      rank: true,
      logo: true,
      nome: true,
      tag: false,
      grupo: false,
      variacao: true,
      quedas: true,
      booyahs: true,
      kills: true,
      pontos: true,
    },
    columnsOrder: ['rank', 'logo', 'nome', 'tag', 'grupo', 'variacao', 'quedas', 'booyahs', 'kills', 'pontos'],
    columnWidths: {
      rank: 0.52,
      logo: 0.7,
      nome: 2.6,
      variacao: 0.72,
      quedas: 0.72,
      booyahs: 0.72,
      kills: 0.85,
      pontos: 0.92,
    },
    layout: {
      x: 185,
      y: 455,
      w: 1550,
      maxRows: 12,
      blockCount: 2,
      rowsPerBlock: 6,
      blockDirection: 'horizontal',
      blockGap: 72,
      headerHeight: 45,
      rowHeight: 63,
      rowGap: 14,
      fontSize: 24,
      logoSize: 44,
      paddingX: 14,
      radius: 0,
    },
  }),
}
