import {
  defaultTabelaGeralConfig,
  mergeOverlayConfig,
  type FixedStreamOverlayTemplate,
} from '@/lib/streamOverlay'

export const mvpGeralOverlayTemplate: FixedStreamOverlayTemplate = {
  id: 'mvp-geral',
  slug: 'mvp-geral',
  nome: 'MVP Geral',
  categoria: 'estatisticas',
  descricao: 'Ranking geral de MVP por abates, com destaque do TOP 1 e tabela TOP 2 ao 8.',
  config_padrao: mergeOverlayConfig(defaultTabelaGeralConfig, {
    title: 'LÍDERES DE ABATES',
    mvpGeral: {
      enabled: true,
      title: 'MVP GERAL',
      tableTitle: 'LÍDERES DE ABATES',
      photoX: 215,
      photoY: 90,
      photoW: 595,
      photoH: 650,
      photoFit: 'cover',
      infoX: 215,
      infoY: 740,
      infoW: 595,
      infoH: 210,
      tableX: 905,
      tableY: 145,
      tableW: 800,
      tableRowHeight: 74,
      tableGap: 12,
      cardBackground: '#7ea51d',
      tableBackground: '#7ea51d',
      lineColor: '#ffffff',
    },
    tabelaGeral: {
      mode: 'lateral',
      backgroundImage: '',
      backgroundOpacity: 0,
      infoImage: {
        enabled: false,
        url: '',
        x: 0,
        y: 0,
        w: 0,
        h: 0,
        opacity: 0,
        fit: 'contain',
      },
    },
    brand: {
      enabled: true,
      imageEnabled: true,
      textEnabled: true,
      logoDataUrl: null,
      name: 'MVP',
      title: 'MVP GERAL',
      x: 215,
      y: 90,
      w: 595,
      h: 650,
      scale: 100,
      opacity: 100,
      objectFit: 'cover',
      objectPosition: 'center center',
      textX: 215,
      textY: 740,
      textW: 595,
      textH: 210,
      textScale: 100,
      textOpacity: 100,
      textColor: '#ffffff',
      nameSize: 42,
      titleSize: 22,
      fontWeight: 900,
      italic: false,
    },
    theme: {
      primary: '#ef1b1b',
      secondary: '#f97316',
      background: 'transparent',
      rowBackground: '#7ea51d',
      rowAltBackground: '#7ea51d',
      text: '#ffffff',
      headerText: '#27272a',
      accent: '#7ea51d',
      border: '#ef1b1b',
      borderColor: '#ef1b1b',
      borderWidth: 0,
      shadow: 'transparent',
    },
    columns: {
      rank: true,
      logo: true,
      nome: true,
      tag: false,
      grupo: false,
      variacao: true,
      quedas: true,
      booyahs: false,
      kills: true,
      pontos: false,
    },
    columnsOrder: ['rank', 'logo', 'nome', 'quedas', 'kills', 'variacao'],
    layout: {
      x: 905,
      y: 145,
      w: 800,
      maxRows: 8,
      blockCount: 1,
      rowsPerBlock: 7,
      blockDirection: 'horizontal',
      blockGap: 0,
      headerHeight: 58,
      rowHeight: 74,
      rowGap: 12,
      fontSize: 30,
      logoSize: 58,
      paddingX: 24,
      radius: 0,
      opacity: 100,
      scale: 100,
    },
  }),
}
