import {
  defaultTabelaGeralConfig,
  mergeOverlayConfig,
  type FixedStreamOverlayTemplate,
} from '@/lib/streamOverlay'

export const mvpGeralOverlayTemplate: FixedStreamOverlayTemplate = {
  id: 'mvp-geral',
  slug: 'mvp-geral',
  nome: 'MVP Geral',
  categoria: 'estatisticas',
  descricao: 'Ranking geral de MVP/lideres de abates com foto do top 1, estatisticas e tabela do top 2 ao 8.',
  config_padrao: mergeOverlayConfig(defaultTabelaGeralConfig, {
    title: 'LÍDERES DE ABATES',
    mvpGeral: {
      enabled: true,
      backgroundImage: '',
      backgroundOpacity: 100,
      photoFit: 'cover',
      tableTitle: 'LÍDERES DE ABATES',
      tableMaxRows: 8,
    },
    tabelaGeral: {
      mode: 'lateral',
      backgroundImage: '',
      backgroundOpacity: 100,
      infoImage: {
        enabled: true,
        url: '',
        x: 210,
        y: 86,
        w: 590,
        h: 650,
        opacity: 100,
        fit: 'cover',
      },
    },
    brand: {
      enabled: true,
      imageEnabled: false,
      textEnabled: true,
      name: 'MVP GERAL',
      title: 'LÍDERES DE ABATES',
      textX: 210,
      textY: 734,
      textW: 590,
      textH: 190,
      textScale: 100,
      textOpacity: 100,
      textColor: '#ffffff',
      fontWeight: 900,
    },
    theme: {
      primary: '#ff5b00',
      secondary: '#7ea11e',
      background: '#f4f1df',
      rowBackground: '#82a51d',
      rowAltBackground: '#82a51d',
      text: '#ffffff',
      headerText: '#2a2a2a',
      accent: '#7ea11e',
      border: '#ff5b00',
      borderColor: '#ff5b00',
      borderWidth: 0,
      shadow: 'transparent',
    },
    columns: {
      rank: true,
      logo: true,
      nome: true,
      tag: false,
      grupo: false,
      variacao: true,
      quedas: true,
      booyahs: false,
      kills: true,
      pontos: false,
    },
    columnsOrder: ['rank', 'logo', 'nome', 'quedas', 'kd', 'kills', 'variacao'],
    layout: {
      x: 900,
      y: 130,
      w: 800,
      maxRows: 8,
      blockCount: 1,
      rowsPerBlock: 7,
      blockDirection: 'horizontal',
      blockGap: 0,
      headerHeight: 44,
      rowHeight: 74,
      rowGap: 12,
      fontSize: 27,
      logoSize: 58,
      paddingX: 12,
      radius: 0,
      scale: 100,
      opacity: 100,
    },
  }),
}
