import {
  defaultTabelaGeralConfig,
  mergeOverlayConfig,
  type FixedStreamOverlayTemplate,
} from '@/lib/streamOverlay'

export const mvpGeralOverlayTemplate: FixedStreamOverlayTemplate = {
  id: 'mvp-geral',
  slug: 'mvp-geral',
  nome: 'MVP Geral',
  categoria: 'estatisticas',
  descricao: 'Ranking geral de MVP por abates, com destaque do TOP 1 e tabela TOP 2 ao 10.',
  config_padrao: mergeOverlayConfig(defaultTabelaGeralConfig, {
    title: 'MVP GERAL',
    mvpGeral: {
      enabled: true,
      title: 'MVP GERAL',
      tableTitle: '',
      tableMaxRows: 10,
      photoX: 210,
      photoY: 56,
      photoW: 590,
      photoH: 642,
      photoFit: 'cover',
      infoX: 210,
      infoY: 698,
      infoW: 590,
      infoH: 205,
      tableX: 900,
      tableY: 205,
      tableW: 862,
      tableRowHeight: 76,
      tableGap: 12,
      cardBackground: '#8010c8',
      tableBackground: 'linear-gradient(90deg, #d8ab4f 0%, #d8ab4f 18%, #8010c8 18%, #8010c8 100%)',
      lineColor: '#d8ab4f',
    },
    tabelaGeral: {
      mode: 'lateral',
      backgroundImage: '',
      backgroundOpacity: 0,
      infoImage: {
        enabled: false,
        url: '',
        x: 0,
        y: 0,
        w: 0,
        h: 0,
        opacity: 0,
        fit: 'contain',
      },
    },
    brand: {
      enabled: true,
      imageEnabled: true,
      textEnabled: true,
      logoDataUrl: null,
      name: 'MVP',
      title: 'MVP GERAL',
      x: 210,
      y: 56,
      w: 590,
      h: 642,
      scale: 100,
      opacity: 100,
      objectFit: 'cover',
      objectPosition: 'center center',
      textX: 210,
      textY: 698,
      textW: 590,
      textH: 205,
      textScale: 100,
      textOpacity: 100,
      textColor: '#ffffff',
      nameSize: 42,
      titleSize: 22,
      fontWeight: 900,
      italic: false,
    },
    theme: {
      primary: '#d8ab4f',
      secondary: '#8010c8',
      background: 'transparent',
      rowBackground: 'linear-gradient(90deg, #d8ab4f 0%, #d8ab4f 18%, #8010c8 18%, #8010c8 100%)',
      rowAltBackground: 'linear-gradient(90deg, #d8ab4f 0%, #d8ab4f 18%, #8010c8 18%, #8010c8 100%)',
      text: '#ffffff',
      headerText: '#050505',
      accent: '#8010c8',
      border: '#d8ab4f',
      borderColor: '#d8ab4f',
      borderWidth: 0,
      shadow: 'transparent',
    },
    columns: {
      rank: true,
      logo: true,
      nome: true,
      tag: false,
      grupo: false,
      variacao: true,
      quedas: true,
      booyahs: false,
      kills: true,
      pontos: false,
    },
    columnsOrder: ['rank', 'logo', 'nome', 'variacao', 'quedas', 'kills'],
    layout: {
      x: 900,
      y: 205,
      w: 862,
      maxRows: 10,
      blockCount: 1,
      rowsPerBlock: 9,
      blockDirection: 'horizontal',
      blockGap: 0,
      headerHeight: 0,
      rowHeight: 76,
      rowGap: 12,
      fontSize: 30,
      logoSize: 58,
      paddingX: 24,
      radius: 0,
      opacity: 100,
      scale: 100,
    },
  }),
}
